### ISSUE TITLE
Example of how to use metalsmith-dev with the .use() pipeline

### ISSUE THREAD

**Issue by jdsimcoe** [geoffb/metalsmith-dev#2]
@geoffb Here is my Metalsmith `build.js` file:

```js
var metalsmith = require('metalsmith'),
    path = require('path'),
    markdown = require('metalsmith-markdown'),
    templates = require('metalsmith-templates'),
    sass = require('metalsmith-sass'),
    dev = require('metalsmith-dev'),
    webpack = require('metalsmith-webpack'),
    excerpts = require('metalsmith-excerpts'),
    collections = require('metalsmith-collections'),
    branch = require('metalsmith-branch'),
    permalinks = require('metalsmith-permalinks'),
    feed = require('metalsmith-feed'),
    wordcount = require('metalsmith-word-count'),
    sitemap = require('metalsmith-sitemap'),
    moment = require('moment');

var siteBuild = metalsmith(__dirname)
    .metadata({
      site: {
        title: 'Circle',
        url: 'http://meetcircle.com'
      }
    })
    .source('./src')
    .destination('./build')
    .use(markdown())
    .use(excerpts())
    .use(collections({
      pages: {
        pattern: '*.html',
        sortBy: 'order',
        reverse: false
      },
      posts: {
        pattern: 'posts/**.html',
        sortBy: 'publishDate',
        reverse: true
      }
    }))
    .use(branch('posts/**.html')
        .use(permalinks({
          pattern: 'posts/:title',
          relative: false
        }))
    )
    .use(branch('!posts/**.html')
        .use(branch('!index.md').use(permalinks({
          relative: false
        })))
    )
    .use(wordcount({
      metaKeyCount: "wordCount",
      metaKeyReadingTime: "readingTime",
      speed: 300,
      seconds: false,
      raw: false
    }))
    .use(templates({
      engine: 'jade',
      moment: moment
    }))
    .use(sass({
      outputDir: 'css/',
      outputStyle: 'compressed'
    }))
    .use(webpack({
      context: path.resolve(__dirname, 'src/js/'),
      entry: './index.js',
      output: {
        path: path.resolve(__dirname, 'build/js/'),
        filename: 'bundle.js'
      }
    }))
    .use(feed({collection: 'posts'}))
    .use(sitemap({
      output: 'sitemap.xml',
      urlProperty: 'path',
      hostname: 'http://meetcircle.com',
      defaults: {
        priority: 0.5,
        changefreq: 'daily'
      }
    }));
if (process.env.NODE_ENV !== 'production') {
  siteBuild = siteBuild
    .use(sass({
      outputDir: 'css/',
      outputStyle: 'expanded'
    }))
    dev.watch(siteBuild);
    dev.serve(siteBuild);
}
siteBuild.build(function (err) {
  if (err) {
    console.log(err);
  }
  else {
    console.log('Site build complete!');
  }
});
```

It doesn't work and I can't figure out how to successfully use your methodology with the default Metalsmith pipeline. A quick example with my existing setup would be very helpful.

**Comment by geoffb** [comment]
@jdsimcoe Are you seeing any errors in the terminal? You should see something like this:

```
[metalsmith-dev] Serving on port 8080
[metalsmith-dev] Watching for changes...
```

**Comment by jdsimcoe** [comment]
@geoffb I tweaked my `build.js` file slightly:

```
var metalsmith = require('metalsmith'),
    path = require('path'),
    markdown = require('metalsmith-markdown'),
    templates = require('metalsmith-templates'),
    sass = require('metalsmith-sass'),
    dev = require('metalsmith-dev'),
    webpack = require('metalsmith-webpack'),
    excerpts = require('metalsmith-excerpts'),
    collections = require('metalsmith-collections'),
    branch = require('metalsmith-branch'),
    permalinks = require('metalsmith-permalinks'),
    feed = require('metalsmith-feed'),
    wordcount = require('metalsmith-word-count'),
    sitemap = require('metalsmith-sitemap'),
    moment = require('moment');

var siteBuild = metalsmith(__dirname)
    .metadata({
      site: {
        title: 'Circle',
        url: 'http://meetcircle.com'
      }
    })
    .source('./src')
    .destination('./build')
    .use(markdown())
    .use(excerpts())
    .use(collections({
      pages: {
        pattern: '*.html',
        sortBy: 'order',
        reverse: false
      },
      posts: {
        pattern: 'posts/**.html',
        sortBy: 'publishDate',
        reverse: true
      }
    }))
    .use(branch('posts/**.html')
        .use(permalinks({
          pattern: 'posts/:title',
          relative: false
        }))
    )
    .use(branch('!posts/**.html')
        .use(branch('!index.md').use(permalinks({
          relative: false
        })))
    )
    .use(wordcount({
      metaKeyCount: "wordCount",
      metaKeyReadingTime: "readingTime",
      speed: 300,
      seconds: false,
      raw: false
    }))
    .use(templates({
      engine: 'jade',
      moment: moment
    }))
    .use(sass({
      outputDir: 'css/',
      outputStyle: 'compressed'
    }))
    .use(webpack({
      context: path.resolve(__dirname, 'src/js/'),
      entry: './index.js',
      output: {
        path: path.resolve(__dirname, 'build/js/'),
        filename: 'bundle.js'
      }
    }))
    .use(feed({collection: 'posts'}))
    .use(sitemap({
      output: 'sitemap.xml',
      urlProperty: 'path',
      hostname: 'http://meetcircle.com',
      defaults: {
        priority: 0.5,
        changefreq: 'daily'
      }
    }));
if (process.env.NODE_ENV !== 'production') {
  siteBuild = siteBuild
    dev.watch(siteBuild)
    dev.serve(siteBuild)
    .use(sass({
      outputDir: 'css/',
      outputStyle: 'expanded'
    }))
}
siteBuild.build(function (err) {
  if (err) {
    console.log(err);
  }
  else {
    console.log('Site build complete!');
  }
});
```
Here is the output in Terminal:

```log
/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/node_modules/globule/lib/globule.js:25
    if (pattern.indexOf('!') === 0) {
               ^
TypeError: Cannot read property 'indexOf' of undefined
    at /Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/node_modules/globule/lib/globule.js:25:16
    at Array.reduce (native)
    at processPatterns (/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/node_modules/globule/lib/globule.js:24:30)
    at Object.globule.find (/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/node_modules/globule/lib/globule.js:76:17)
    at Gaze.add (/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/lib/gaze.js:174:19)
    at new Gaze (/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/lib/gaze.js:74:10)
    at gaze (/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/node_modules/gaze/lib/gaze.js:86:10)
    at Object.exports.watch (/Users/jdsimcoe/Sites/website-test/node_modules/metalsmith-dev/lib/dev.js:16:2)
    at Object.<anonymous> (/Users/jdsimcoe/Sites/website-test/build.js:86:9)
    at Module._compile (module.js:460:26)
```

**Comment by geoffb** [comment]
The error seems to be that the array of paths to watch for changes isn't an array.

I'm not sure what's happening with this code:

```
siteBuild = siteBuild
    dev.watch(siteBuild)
    dev.serve(siteBuild)
    .use(sass({
      outputDir: 'css/',
      outputStyle: 'expanded'
    }))
```

The `metalsmith-dev` functions don't return an instance of `metalsmith`. Seems like you'd want something more like this:

```
siteBuild.use(sass({
  outputDir: 'css/',
  outputStyle: 'expanded'
}));

dev.watch(siteBuild);
dev.serve(siteBuild);
```

Here's an example of how I'm using it: https://github.com/geoffb/www.geoffblair.com/blob/master/build.js#L62

**Comment by geoffb** [comment]
I had time to look into this further and found an error when omitting the extra paths to the `watch` method. Should be fixed now.

**Comment by jdsimcoe** [comment]
Cool, thanks!

**Comment by jdsimcoe** [comment]
@geoffb Got this working. Does `metalsmith-dev` support LiveReload at all?
